name: Release 
on: 
  push: 
    branches: [ master ]

permissions:
  contents: write
  issues: write
  pull-requests: write

# canceling of previous CI run (if such exists)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs: 
  release: 
    runs-on: ubuntu-latest 
 
    steps: 
      - name: Checkout 
        uses: actions/checkout@v2 
 
      - name: Setup Node.js 
        uses: actions/setup-node@v2 
        with: 
          node-version: '14' 
 
      - name: Release to GitHub 
        uses: cycjimmy/semantic-release-action@v2.5.4 
        with: 
          semantic_version: 18.0.0 
          extra_plugins: | 
            @semantic-release/changelog@5.0.1 
            @semantic-release/git 
          branches: | 
            ['master'] 
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
